export class Aluno {
  id!: number;
  nome!: string;
  cpf!: string;
  ra!: string;
  dataCadastro!: string;
  dataNascimento!: string;
  sexo!: string;
  nomeMae!: string;
  cpfMae!: string;
  nomePai!: string;
  cpfPai!: string;
  nomeResponsavel!: string;
  cpfResponsavel!: string;
  nomeEscola!: string;
  nomeProfessor!: string;
  serieEscolar!: string;
  periodoEscolar!: string;
  nomeProfessorEspecial!: string;
  necessitaCuidador!: string;
  cuidador!: string;
  deficiencia!: string;
  contatoMae1!: string;
  contatoPai1!: string;
  contatoMae2!: string;
  contatoPai2!: string;
  contatoResponsavel1!: string;
  contatoResponsavel2!: string;
  logradouro!: string;
  numero!: string;
  bairro!: string;
  cidade!: string;
  estado!: string;
  cep!: string;
  resumoAluno!: string;
  outrasInfos!: string;
  relatorioMedico!: string;
  relatorioPedagogico!: string;

  constructor() {}
}
